config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  devise_for :users
  resources :enemies
  resources :quests
  resources :items
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  belongs_to :location
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  def get_rarity
    rarity_hash = { 1..50 => 'Common', 51..75 => 'Uncommon', 76..88 => 'Rare', 89..95 => 'Epic', 96..99 => 'Legendary' }
    rarity_hash.select {|rarity| rarity === self.rarity}.values.first 
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :enemies
  has_many :users
   # * Do we need has many users here?
end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_one :location
  has_many :items
  has_many :quests
  #after_initialize :init

  # first approach ->
  # def init
  #   self.location_id = 1
  # end
  # An approach -> attribute :location_id, :integer, default: 1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  @locations =Location.all
end

app/controllers/items_controller.rb
require 'faker'
class ItemsController < ApplicationController

  before_action :authenticate_user!
  def index
    @items = Item.all
    @locations = Location.all
    render :index
  end

  def new
    @item = Item.new
    @locations = Location.all
    render :new
  end

  def create
    #@item = Item.new(item_params)
    @item = Item.new(name: Faker::Games::DnD.melee_weapon, rarity: rand(1..99), user_id: current_user.id)
    @locations = Location.all
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    render :edit
  end
  
  def show
    @item = Item.find(params[:id])
    
    render :show
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    redirect_to items_path
  end

  def get_rarity
    rarity_hash = { 1..50 => 'Common', 51..75 => 'Uncommon', 76..88 => 'Rare', 89..95 => 'Epic', 96..99 => 'Legendary' }
    rarity_hash.select {|rarity| rarity === self.rarity}.values.first 
  end

  private 
    def item_params
      params.require(:item).permit(:name, :rarity)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  before_action :authenticate_user!
  def index
    @locations = Location.all
    before_action :authenticate_user!
    render "layouts/locations", :object => @locations
  end

  def new
    @location = Location.new
    render :new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
    render :edit
  end
  
  def show
    @location = Location.find(params[:id])
    @locations =Location.all
    render :show
  end

  def update
    @location = Location.find(params[:id])
    if @location.update(location_params)
      redirect_to locations_path
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    redirect_to locations_path
  end

  private 
    def location_params
      params.require(:location).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<% if @items.any?%>
<h3 class='text-nowrap'>Items you  found on your quest: </h3>
  <% @items.each do |item| %>
    <h4><%= item.name %> (<%= item.get_rarity %>)</h4>
  <% end %>
<% else%>
  The elves haven't crafted any items yet.
<% end %>

app/views/items/new.html.erb
<br>
<%= form_for @item do |f| %>
<%= f.submit "Reveal the item"%>
<% end %>

app/views/items/show.html.erb
<%# <h6></h6>
<h5><h5>
<h4></h4>
<h3></h3>
<h2></h2>
<h1></h1> %>

app/views/layouts/_items.html.erb
<br>
<% if user_signed_in?%>
<em><%= link_to 'Open a chest!', new_item_path %></em>
<%end%>

app/views/layouts/_locations.html.erb
<% if user_signed_in?%>
<h2>Travel to: </h2>
<div class="text-nowrap">
<span class="text-nowrap"><% @locations.each do |location| %> <%= link_to location.name, location_path(location) %></span>
  <% end %>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<a href='/' class='title'>Quest on Rails</a></div>
<br>
      <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign up", '/users/sign_up' %> | <%= link_to "Sign in", '/users/sign_in' %>
    <% end %>
<p class='smol'>click above to return to the homepage.</p>
<hr>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/locations" %>
        <%= render "layouts/items" %>
  <br>
    <%= yield %>
  </body>
</html>

app/views/locations/show.html.erb
<br>
<br>
<h6>You've arrived at </h6>
<span><h3><%=@location.name %></h3></span>